#!/usr/bin/env bash

. ./node_modules/release-util-fnd/lib.sh

pre_release_checks
npm test

target_dir=`create_package`
# include pre-compiled bundle
npm run compile
cp ./dist/embeddable-content.js "$target_dir/"

publish_package
